### ISSUE TITLE
Crash when opening the menu

### ISSUE THREAD

**Issue by NatoBoram** [MrTroot/autofish#2]
Hello! I might have a particularly crashy setup, but I'd like you to look into it. When I press the key to open AutoFish' settings, Minecraft crashes.

```yaml
Minecraft: 1.16.3
Fabric Installer: 0.6.1.51
Java: openjdk 14.0.2 2020-07-14
Mods:
  - Autofish-0.9.0-fabric-mc1.16.jar
  - fabric-api-0.23.0+build.410-1.16.jar
  - fabricmod_VoxelMap-1.10.11_for_1.16.3.jar
  - inventoryprofiles-fabric-1.16.2-0.4.2.jar
  - litematica-fabric-1.16.3-0.0.0-dev.20200913.215807.jar
  - malilib-fabric-1.16.3-0.10.0-dev.21+arne.1.jar
  - optifabric-1.6.4.jar
  - preview_OptiFine_1.16.3_HD_U_G4_pre2.jar
```

```yaml
OS: Windows 10 Pro x86_64
Kernel: 10.0.19041
Uptime: 1 hour, 31 mins
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Custom
CPU: Intel i5-3570K (4) @ 3.470GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 10710MiB / 24519MiB
```

It would also be nice if you could add an issue template so we can know what you need to know to look into the issue.

[crash-2020-10-10_16.12.04-client.txt](https://github.com/MrTroot/autofish/files/5359947/crash-2020-10-10_16.12.04-client.txt)
